services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: kyler
      POSTGRES_PASSWORD: Icedog2026!
      POSTGRES_DB: aeromaps_development
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails server -b '0.0.0.0'"
    volumes:
      - ".:/aeromaps"
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://kyler:Icedog2026!@db/aeromaps_development
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
