default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: aeromaps_development
  username: kyler
  password: <%= ENV['DB_PASSWORD'] %>

test:
  <<: *default
  database: aeromaps_test
  username: kyler
  password: <%= ENV['DB_PASSWORD'] %>

production:
  <<: *default
  database: aeromaps_production
  username: kyler
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>
  pool: 5
  timeout: 5000
